sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: USfTeb0sA7URLwGbCwkOJqThRJjpcIZf33QsjZvWCGlMfSJ5lia4EO/p/bK55Hmbq96ilyeGnJdpu4KMTJJaG6XJE6jQ5fsWrqn3cNINcNTZ3xqAZKr3Ac+0jYl1BMpf1c2HOW2gdrjDXffVC2uSuwnNnM9Z8YJHarSxn7bc8gDVKvu/fqbfqAEd59raqkzNkMmYJ0LYnjaSiQMGKG3JoCsBp7zdAIx4thUub0k167SSwbLXBW1ZyLj9yxCc2iTr08oNXBm3gCsd+OQOfzg04620ayeib0dQy/Hl1vemEsG1hSnC29C+ZKr9ndpc1a247fxQy2NbwNJhL+8fJSSbW/QaGII4hZ1tlJ4nsc/qBf3sZEV3oqGqw8dXSVhVzfQ9U3sWgFW7X5Uxx8ZLlho1n8SPi4K3/94V4ZV6cqIEMvMr8l+YL/IQMA6w/O/mo2W1KVm1e7Q3CsGtJkqXwHGoyG3muXQ07vK9SfBySe/H8aDh76EKJy58S8n9cA5AJU9RLLpYyGNtVTR/qjuHZ2dhIVU7utwDqZYvk2cbCvbDeO/jvCs59n+C1Oomc5Ham5xjAe9Y337Cz9gqXfZamLxKm+9qp0XFGGMTF0Oc2xqDhDQQ6D4hMitpJl56bYjw858shO1eHN/KcvoHGp9K0fV/LXJIQKuBEm+dyc7qP3SQKiA=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Notes-of-a-War-Correspondent_3050
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy